{
 "title": "first dashborad",
 "description": "cpu",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Storage Serveur Sopra 2",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node3\", mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"node3\", mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Sopra Server",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", job=\"node2\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\", job=\"node2\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Local",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", instance=\"localhost:9100\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"localhost:9100\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SQL service Sopra Server",
   "type": "gauge",
   "description": "state du service sql sur la vm node2",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node2\", name=\"mysql.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Service",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node2\", name=\"apache2.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask Service Sopra Server",
   "type": "gauge",
   "description": "il permet de soliciter webhook pour envoyer les log dans teams",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node2\", name=\"flask_webhook.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Local",
   "type": "timeseries",
   "description": "0-100%",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": " - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"node\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Local",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node\"} / node_memory_MemTotal_bytes{job=\"node\"}))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Sopra Server",
   "type": "timeseries",
   "description": "0-100%",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": " - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"node2\"}[5m])) * 100)",
     "legendFormat": "{{label_name}}selim"
    }
   ]
  },
  {
   "title": "Ollama Service",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"ollama.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected User on Node3",
   "type": "bargauge",
   "description": "node3",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connected_users{job=\"node3\"}",
     "legendFormat": "node3"
    },
    {
     "expr": "connected_users{job=\"node\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 13 },
   "options": {
    "content": "<a href=\"http://localhost:5000/hello\" target=\"_blank\" >\n <h1> Say hello </h1>\n\n</a>"
   }
  }
 ]
}